name: 'Package build'
description: 'Build a package'
runs:
  using: "composite"
  steps:
    - name: build
      run: |
      docker run --rm --privileged aptman/qus -s -- -p aarch64
      docker run --platform=linux/arm64 -v $GITHUB_ACTION_PATH:$GITHUB_ACTION_PATH "/bin/bash" "./actionscript.sh"
      shell: bash
