name: 'Package build'
description: 'Build a package'
inputs: 
  arch:
    description: Architecture to run on (x86_64, aarch64)
    required: true
runs:
  using: "composite"
  steps:
    - name: build
      run: |
      echo $arch
#      docker run --rm --privileged aptman/qus -s -- -p aarch64
#      docker run --rm --platform=linux/arm64 -v $GITHUB_ACTION_PATH:$GITHUB_ACTION_PATH "/bin/bash" "./actionscript.sh"
#      shell: bash
