name: 'Package build'
description: 'Build a package'
inputs: 
  arch:
    description: Architecture to run on (x86_64, aarch64)
    required: true
runs:
  using: "composite"
  steps:
    - name: build
      run: |
        printenv 
      shell: bash